### ISSUE TITLE
tweet.proto looks useful - please add a license

### ISSUE THREAD

**Issue by ehiggs** [LesTR/nodejs-protobuf-benchmark#1]
Hi,
Tweet.proto looks really useful. Could you add a license to the project so I know whether it's available for use and further distribution? Or do you consider it to be a direct description of the twitter API and therefore a description of fact and hence not copyrightable?

Thanks~

**Comment by LesTR** [comment]
Added but that proto file may be outdated. It was created just for this benchmark.

**Comment by ehiggs** [comment]
Thanks!

It does indeed seem to be outdated. But it looks like a good starting point.
